/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author alves
 */
public class Cinzas extends javax.swing.JDialog {

    /**
     * Creates new form Cizas
     */
    public Cinzas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtresultadocin2 = new javax.swing.JTextField();
        txtresultadocin1 = new javax.swing.JTextField();
        txtamostracin3 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtfinalcin3 = new javax.swing.JTextField();
        btncalcularcin2 = new javax.swing.JButton();
        txtmediacinzas = new javax.swing.JTextField();
        btncalcularcin1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtcadinhocin2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtcadinhocin1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtamostracin1 = new javax.swing.JTextField();
        txtfinalcin2 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtfinalcin1 = new javax.swing.JTextField();
        txtcalcularcin3 = new javax.swing.JButton();
        txtamostracin2 = new javax.swing.JTextField();
        btnmediacinzas = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtresultadocin3 = new javax.swing.JTextField();
        txtcadinhocin3 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnInserirCinzas = new javax.swing.JButton();
        btnDesvioPadraoUmidade = new javax.swing.JButton();
        txtDesvioPadraoCinzas = new javax.swing.JTextField();
        btnvarianciacin = new javax.swing.JButton();
        txtvarianciacin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CALCEN");

        jLabel19.setText("P. Final");

        btncalcularcin2.setText("Calcular:");
        btncalcularcin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularcin2ActionPerformed(evt);
            }
        });

        btncalcularcin1.setText("Calcular:");
        btncalcularcin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularcin1ActionPerformed(evt);
            }
        });

        jLabel7.setText("P. Cadinho Vazio");

        txtcadinhocin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcadinhocin2ActionPerformed(evt);
            }
        });

        jLabel20.setText("P. Amostra");

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel21.setText("Amostra 1:");

        jLabel22.setText("P. Cadinho Vazio");

        txtcadinhocin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcadinhocin1ActionPerformed(evt);
            }
        });

        jLabel23.setText("P. Amostra");

        jLabel24.setText("P. Final");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setText("Amostra 2:");

        txtcalcularcin3.setText("Calcular:");
        txtcalcularcin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcalcularcin3ActionPerformed(evt);
            }
        });

        btnmediacinzas.setText("Média");
        btnmediacinzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmediacinzasActionPerformed(evt);
            }
        });

        jLabel25.setText("P. Final");

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel16.setText("Amostra 3:");

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Cinzas");

        jLabel17.setText("P. Cadinho Vazio");

        txtcadinhocin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcadinhocin3ActionPerformed(evt);
            }
        });

        jLabel18.setText("P. Amostra");

        btnInserirCinzas.setText("Inserir");
        btnInserirCinzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirCinzasActionPerformed(evt);
            }
        });

        btnDesvioPadraoUmidade.setText("Desvio Padrão");
        btnDesvioPadraoUmidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesvioPadraoUmidadeActionPerformed(evt);
            }
        });

        btnvarianciacin.setText("Variância");
        btnvarianciacin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvarianciacinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnvarianciacin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnmediacinzas, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtvarianciacin)
                            .addComponent(txtmediacinzas, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnDesvioPadraoUmidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDesvioPadraoCinzas, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnInserirCinzas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(246, 246, 246)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel16)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtcadinhocin2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtcadinhocin3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtcadinhocin1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtamostracin2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtamostracin3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtamostracin1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtfinalcin3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtfinalcin2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtfinalcin1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btncalcularcin1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtresultadocin1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtcalcularcin3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtresultadocin3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btncalcularcin2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtresultadocin2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtcadinhocin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22)
                                .addComponent(jLabel23)
                                .addComponent(txtamostracin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel24)
                                .addComponent(txtfinalcin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btncalcularcin1)
                                .addComponent(txtresultadocin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(txtamostracin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25)
                                    .addComponent(txtfinalcin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btncalcularcin2)
                                    .addComponent(txtresultadocin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel21)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtcadinhocin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(33, 33, 33))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtcadinhocin3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17)
                                .addComponent(jLabel18)
                                .addComponent(txtamostracin3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19)
                                .addComponent(txtfinalcin3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtcalcularcin3)
                                .addComponent(txtresultadocin3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDesvioPadraoCinzas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDesvioPadraoUmidade)
                    .addComponent(txtmediacinzas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmediacinzas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserirCinzas)
                    .addComponent(btnvarianciacin)
                    .addComponent(txtvarianciacin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncalcularcin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularcin2ActionPerformed
        // TODO add your handling code here:
        double vc1, vc2, vc3, resultcin2, mediacin2;

        vc1 = Double.parseDouble (txtcadinhocin2.getText());
        vc2 = Double.parseDouble(txtamostracin2.getText());
        vc3 = Double.parseDouble(txtfinalcin2.getText());

        resultcin2 = ((vc3-vc1)*100) / vc2;

        txtresultadocin2.setText(String.valueOf(resultcin2));
    }//GEN-LAST:event_btncalcularcin2ActionPerformed

    private void btncalcularcin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularcin1ActionPerformed
        // TODO add your handling code here:
        double vc1, vc2, vc3, resultcin, mediacin;

        vc1 = Double.parseDouble (txtcadinhocin1.getText());
        vc2 = Double.parseDouble(txtamostracin1.getText());
        vc3 = Double.parseDouble(txtfinalcin1.getText());

        resultcin = ((vc3-vc1)*100) / vc2;

        txtresultadocin1.setText(String.valueOf(resultcin));
    }//GEN-LAST:event_btncalcularcin1ActionPerformed

    private void txtcadinhocin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcadinhocin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcadinhocin2ActionPerformed

    private void txtcadinhocin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcadinhocin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcadinhocin1ActionPerformed

    private void txtcalcularcin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcalcularcin3ActionPerformed
        // TODO add your handling code here:
        double vc1, vc2, vc3, resultcin3, mediacin3;

        vc1 = Double.parseDouble (txtcadinhocin3.getText());
        vc2 = Double.parseDouble(txtamostracin3.getText());
        vc3 = Double.parseDouble(txtfinalcin3.getText());

        resultcin3 = ((vc3-vc1)*100) / vc2;

        txtresultadocin3.setText(String.valueOf(resultcin3));
    }//GEN-LAST:event_txtcalcularcin3ActionPerformed

    private void btnmediacinzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmediacinzasActionPerformed
        // TODO add your handling code here:
        double resultcin, resultcin2, resultcin3, mediacinzas;

        resultcin = Double.parseDouble(txtresultadocin1.getText());
        resultcin2 = Double.parseDouble(txtresultadocin2.getText());
        resultcin3 = Double.parseDouble(txtresultadocin3.getText());

        mediacinzas = (resultcin + resultcin2 + resultcin3) / 3;

        txtmediacinzas.setText(String.valueOf(mediacinzas));
    }//GEN-LAST:event_btnmediacinzasActionPerformed

    private void txtcadinhocin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcadinhocin3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcadinhocin3ActionPerformed

    private void btnInserirCinzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirCinzasActionPerformed
        // TODO add your handling code here:
        this.hide ();
        this.dispose();
    }//GEN-LAST:event_btnInserirCinzasActionPerformed

    private void btnDesvioPadraoUmidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesvioPadraoUmidadeActionPerformed
        double n1, n2, n3, somatoriocin1, somatoriocin2, somatoriocin3, varianciacin, despadraocin;
        double resultcin, resultcin2, resultcin3, mediacinzas;
        
        resultcin = Double.parseDouble(txtresultadocin1.getText());
        resultcin2 = Double.parseDouble(txtresultadocin2.getText());
        resultcin3 = Double.parseDouble(txtresultadocin3.getText());       
        mediacinzas = (resultcin + resultcin2 + resultcin3) / 3;     
        
        n1 = Double.parseDouble (txtresultadocin1.getText());
        n2 = Double.parseDouble(txtresultadocin2.getText());
        n3 = Double.parseDouble(txtresultadocin3.getText());
        somatoriocin1 = Math.pow(n1-mediacinzas,2);     
        somatoriocin2 = Math.pow(n2-mediacinzas,2);
        somatoriocin3 = Math.pow(n3-mediacinzas,2);

        varianciacin = somatoriocin1+somatoriocin2+somatoriocin3/3;
        txtvarianciacin.setText(String.valueOf(varianciacin));
        
        despadraocin = Math.sqrt (varianciacin);
        
        txtDesvioPadraoCinzas.setText(String.valueOf(despadraocin));

    }//GEN-LAST:event_btnDesvioPadraoUmidadeActionPerformed

    private void btnvarianciacinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvarianciacinActionPerformed
        // TODO add your handling code here:
        double n1, n2, n3, somatoriocin1, somatoriocin2, somatoriocin3, varianciacin;
        double resultcin, resultcin2, resultcin3, mediacinzas;
        
        resultcin = Double.parseDouble(txtresultadocin1.getText());
        resultcin2 = Double.parseDouble(txtresultadocin2.getText());
        resultcin3 = Double.parseDouble(txtresultadocin3.getText());       
        mediacinzas = (resultcin + resultcin2 + resultcin3) / 3;     
        
        n1 = Double.parseDouble (txtresultadocin1.getText());
        n2 = Double.parseDouble(txtresultadocin2.getText());
        n3 = Double.parseDouble(txtresultadocin3.getText());
        somatoriocin1 = Math.pow(n1-mediacinzas,2);     
        somatoriocin2 = Math.pow(n2-mediacinzas,2);
        somatoriocin3 = Math.pow(n3-mediacinzas,2);

        varianciacin = somatoriocin1+somatoriocin2+somatoriocin3/3;
        txtvarianciacin.setText(String.valueOf(varianciacin));
        
    }//GEN-LAST:event_btnvarianciacinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cinzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cinzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cinzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cinzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cinzas dialog = new Cinzas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesvioPadraoUmidade;
    private javax.swing.JButton btnInserirCinzas;
    private javax.swing.JButton btncalcularcin1;
    private javax.swing.JButton btncalcularcin2;
    private javax.swing.JButton btnmediacinzas;
    private javax.swing.JButton btnvarianciacin;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtDesvioPadraoCinzas;
    private javax.swing.JTextField txtamostracin1;
    private javax.swing.JTextField txtamostracin2;
    private javax.swing.JTextField txtamostracin3;
    private javax.swing.JTextField txtcadinhocin1;
    private javax.swing.JTextField txtcadinhocin2;
    private javax.swing.JTextField txtcadinhocin3;
    private javax.swing.JButton txtcalcularcin3;
    private javax.swing.JTextField txtfinalcin1;
    private javax.swing.JTextField txtfinalcin2;
    private javax.swing.JTextField txtfinalcin3;
    private javax.swing.JTextField txtmediacinzas;
    private javax.swing.JTextField txtresultadocin1;
    private javax.swing.JTextField txtresultadocin2;
    private javax.swing.JTextField txtresultadocin3;
    private javax.swing.JTextField txtvarianciacin;
    // End of variables declaration//GEN-END:variables
}
