/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alves
 */
public class TelaInicio extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicio
     */
    public TelaInicio() {
        initComponents();
    }

    
public static void updateTable1    (){
        List<MinhaClasse> list = new ArrayList<>();
        
        DefaultTableModel amostra1 = new DefaultTableModel();
        amostra1.addColumn ("Umidade 1");
        amostra1.addColumn ("Cinzas 1");
        amostra1.addColumn ("Proteínas 1");
        amostra1.addColumn ("Lipidios 1");
        amostra1.addColumn ("Fibras 1");
        amostra1.addColumn ("Carboidratos 1");
        //Adicionando nome nas colunas
        
        for (MinhaClasse mc : list){
            amostra1.addRow (new Object[]{
                mc.v1,
                mc.v2
            });
        }      
}

    void settxtresultado1(JTextField txtresultado1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

private class MinhaClasse   {
    String v1;
    String v2;
    String v3;
    String v4;
    String v5; 
    String v6;
}

public static void updateTable2    (){
        List<MinhaClasse2> list = new ArrayList<>();
        
        DefaultTableModel amostra2 = new DefaultTableModel();
        amostra2.addColumn ("Umidade 2");
        amostra2.addColumn ("Cinzas 2");
        amostra2.addColumn ("Proteínas 2");
        amostra2.addColumn ("Lipidios 2");
        amostra2.addColumn ("Fibras 2");
        amostra2.addColumn ("Carboidratos 2");
        //Adicionando nome nas colunas
        
        for (MinhaClasse2 mc2 : list){
            amostra2.addRow (new Object[]{
                mc2.v1,
                mc2.v2
            });
        }
}

private class MinhaClasse2   {
    String v1;
    String v2;
    String v3;
    String v4;
    String v5; 
    String v6;
}

public static void updateTable3    (){
        List<MinhaClasse3> list = new ArrayList<>();
        
        DefaultTableModel amostra3 = new DefaultTableModel();
        amostra3.addColumn ("Umidade 3");
        amostra3.addColumn ("Cinzas 3");
        amostra3.addColumn ("Proteínas 3");
        amostra3.addColumn ("Lipidios 3");
        amostra3.addColumn ("Fibras 3");
        amostra3.addColumn ("Carboidratos 3");
        //Adicionando nome nas colunas
        
        for (MinhaClasse3 mc3 : list){
            amostra3.addRow (new Object[]{
                mc3.v1,
                mc3.v2
            });
        }
}

private class MinhaClasse3   {
    String v1;
    String v2;
    String v3;
    String v4;
    String v5; 
    String v6;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnFibras = new javax.swing.JButton();
        btnUmidade = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        amostra3 = new javax.swing.JTable();
        btnCinzas = new javax.swing.JButton();
        btnProteinas = new javax.swing.JButton();
        btnCarboidratos = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        amostra1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        amostra2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLipidios = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCEN");

        btnFibras.setText("Fibras");
        btnFibras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFibrasActionPerformed(evt);
            }
        });

        btnUmidade.setText("Umidade");
        btnUmidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUmidadeActionPerformed(evt);
            }
        });

        amostra3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Umidade", "Cinzas", "Proteínas", "Lipídios", "Fibras", "Carboidratos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(amostra3);

        btnCinzas.setText("Cinzas");
        btnCinzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCinzasActionPerformed(evt);
            }
        });

        btnProteinas.setText("Proteínas");
        btnProteinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProteinasActionPerformed(evt);
            }
        });

        btnCarboidratos.setText("Carboidratos");
        btnCarboidratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarboidratosActionPerformed(evt);
            }
        });

        amostra1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Umidade", "Cinzas", "Proteinas", "Lipidios", "Fibras", "Carboidratos"
            }
        ));
        jScrollPane6.setViewportView(amostra1);

        jLabel4.setFont(new java.awt.Font("Goudy Stout", 1, 18)); // NOI18N
        jLabel4.setText("ANÁLISE CENTESIMAL");

        amostra2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Umidade", "Cinzas", "Proteínas", "Lipídios", "Fibras", "Carboidratos"
            }
        ));
        jScrollPane4.setViewportView(amostra2);

        jLabel1.setText("Amostra 3");

        jLabel2.setText("Amostra 2");

        btnLipidios.setText("Lipídios");
        btnLipidios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLipidiosActionPerformed(evt);
            }
        });

        jLabel3.setText("Amostra 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUmidade)
                        .addGap(69, 69, 69)
                        .addComponent(btnCinzas)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(257, 257, 257)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCarboidratos, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnFibras)
                                        .addGap(89, 89, 89)
                                        .addComponent(btnProteinas)
                                        .addGap(191, 191, 191))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(btnLipidios)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(403, 403, 403)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(409, 409, 409)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(401, 401, 401)
                        .addComponent(jLabel1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUmidade)
                    .addComponent(btnCarboidratos)
                    .addComponent(btnProteinas)
                    .addComponent(btnFibras)
                    .addComponent(btnLipidios)
                    .addComponent(btnCinzas))
                .addGap(65, 65, 65)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFibrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFibrasActionPerformed
        // TODO add your handling code here:
        Fibras frame = new Fibras (this,true);
        frame.setVisible(true);
    }//GEN-LAST:event_btnFibrasActionPerformed

    private void btnUmidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUmidadeActionPerformed
        // TODO add your handling code here:
        Umidade frame = new Umidade(this,true);
        frame.setVisible(true);
    }//GEN-LAST:event_btnUmidadeActionPerformed

    private void btnCinzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCinzasActionPerformed
        // TODO add your handling code here:
        Cinzas frame = new Cinzas (this,true);
        frame.setVisible(true);
    }//GEN-LAST:event_btnCinzasActionPerformed

    private void btnProteinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProteinasActionPerformed
        // TODO add your handling code here:
        Proteinas frame = new Proteinas (this,true);
        frame.setVisible(true);
    }//GEN-LAST:event_btnProteinasActionPerformed

    private void btnCarboidratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarboidratosActionPerformed
        // TODO add your handling code here:
        Carboidratos frame = new Carboidratos (this, true);
        frame.setVisible(true);
    }//GEN-LAST:event_btnCarboidratosActionPerformed

    private void btnLipidiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLipidiosActionPerformed
        // TODO add your handling code here:
        Lipidios frame = new Lipidios (this, true);
        frame.setVisible(true);
    }//GEN-LAST:event_btnLipidiosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable amostra1;
    private javax.swing.JTable amostra2;
    private javax.swing.JTable amostra3;
    private javax.swing.JButton btnCarboidratos;
    private javax.swing.JButton btnCinzas;
    private javax.swing.JButton btnFibras;
    private javax.swing.JButton btnLipidios;
    private javax.swing.JButton btnProteinas;
    private javax.swing.JButton btnUmidade;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables

    public void recebeUmidade (String resultado1 ){
        
    }
}
