/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alves
 */
public class TelaInicio extends javax.swing.JFrame {
    
    private Umidade umid;

    /**
     * Creates new form TelaInicio
     */
    public TelaInicio() {
        initComponents();
        
       this.umid = new Umidade (this, true); 
    }
    
       
public static void updateTable1    (){
        List<MinhaClasse> list = new ArrayList<>();
        
        DefaultTableModel amostra1 = new DefaultTableModel();
        amostra1.addColumn ("Umidade 1");
        amostra1.addColumn ("Cinzas 1");
        amostra1.addColumn ("Proteínas 1");
        amostra1.addColumn ("Lipidios 1");
        amostra1.addColumn ("Fibras 1");
        amostra1.addColumn ("Carboidratos 1");
        //Adicionando nome nas colunas
        
        for (MinhaClasse mc : list){
            amostra1.addRow (new Object[]{
                mc.v1,
                mc.v2
            });
        }      
}

    void settxtresultado1(JTextField txtresultado1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

private class MinhaClasse   {
    String v1;
    String v2;
    String v3;
    String v4;
    String v5; 
    String v6;
}

public static void updateTable2    (){
        List<MinhaClasse2> list = new ArrayList<>();
        
        DefaultTableModel amostra2 = new DefaultTableModel();
        amostra2.addColumn ("Umidade 2");
        amostra2.addColumn ("Cinzas 2");
        amostra2.addColumn ("Proteínas 2");
        amostra2.addColumn ("Lipidios 2");
        amostra2.addColumn ("Fibras 2");
        amostra2.addColumn ("Carboidratos 2");
        //Adicionando nome nas colunas
        
        for (MinhaClasse2 mc2 : list){
            amostra2.addRow (new Object[]{
                mc2.v1,
                mc2.v2
            });
        }
}

private class MinhaClasse2   {
    String v1;
    String v2;
    String v3;
    String v4;
    String v5; 
    String v6;
}

public static void updateTable3    (){
        List<MinhaClasse3> list = new ArrayList<>();
        
        DefaultTableModel amostra3 = new DefaultTableModel();
        amostra3.addColumn ("Umidade 3");
        amostra3.addColumn ("Cinzas 3");
        amostra3.addColumn ("Proteínas 3");
        amostra3.addColumn ("Lipidios 3");
        amostra3.addColumn ("Fibras 3");
        amostra3.addColumn ("Carboidratos 3");
        //Adicionando nome nas colunas
        
        for (MinhaClasse3 mc3 : list){
            amostra3.addRow (new Object[]{
                mc3.v1,
                mc3.v2
            });
        }
}

private class MinhaClasse3   {
    String v1;
    String v2;
    String v3;
    String v4;
    String v5; 
    String v6;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnFibras = new javax.swing.JButton();
        btnUmidade = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        amostra3 = new javax.swing.JTable();
        btnCinzas = new javax.swing.JButton();
        btnProteinas = new javax.swing.JButton();
        btnCarboidratos = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        amostra1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        amostra2 = new javax.swing.JTable();
        btnLipidios = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Umidade3table = new javax.swing.JTextField();
        Umidade1table = new javax.swing.JTextField();
        Umidade2table = new javax.swing.JTextField();
        Cinzas1table = new javax.swing.JTextField();
        Cinzas2table = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        Proteinas1table = new javax.swing.JTextField();
        Proteinas2table = new javax.swing.JTextField();
        Lipidios1table = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        Lipidios2table = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        InserirAmostra1 = new javax.swing.JButton();
        InserirAmostra2 = new javax.swing.JButton();
        InserirAmostra3 = new javax.swing.JButton();
        Fibras1table = new javax.swing.JTextField();
        Fibras2table = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        Carboidratos1table = new javax.swing.JTextField();
        Carboidratos2table = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCEN");

        btnFibras.setText("Fibras");
        btnFibras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFibrasActionPerformed(evt);
            }
        });

        btnUmidade.setText("Umidade");
        btnUmidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUmidadeActionPerformed(evt);
            }
        });

        amostra3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Umidade", "Cinzas", "Proteínas", "Lipídios", "Fibras", "Carboidratos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(amostra3);

        btnCinzas.setText("Cinzas");
        btnCinzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCinzasActionPerformed(evt);
            }
        });

        btnProteinas.setText("Proteínas");
        btnProteinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProteinasActionPerformed(evt);
            }
        });

        btnCarboidratos.setText("Carboidratos");
        btnCarboidratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarboidratosActionPerformed(evt);
            }
        });

        amostra1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Umidade", "Cinzas", "Proteinas", "Lipidios", "Fibras", "Carboidratos"
            }
        ));
        jScrollPane6.setViewportView(amostra1);

        jLabel4.setFont(new java.awt.Font("Goudy Stout", 1, 18)); // NOI18N
        jLabel4.setText("ANÁLISE CENTESIMAL");

        amostra2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Umidade", "Cinzas", "Proteínas", "Lipídios", "Fibras", "Carboidratos"
            }
        ));
        jScrollPane4.setViewportView(amostra2);

        btnLipidios.setText("Lipídios");
        btnLipidios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLipidiosActionPerformed(evt);
            }
        });

        Umidade1table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Umidade1tableActionPerformed(evt);
            }
        });

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        InserirAmostra1.setText("Adicionar resultados da amostra 1");
        InserirAmostra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirAmostra1ActionPerformed(evt);
            }
        });

        InserirAmostra2.setText("Adicinar resultado da Amostra2");
        InserirAmostra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirAmostra2ActionPerformed(evt);
            }
        });

        InserirAmostra3.setText("Adicionar resultado Amostra3");

        Fibras2table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fibras2tableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(InserirAmostra2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(418, 418, 418))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(InserirAmostra3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(425, 425, 425))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnUmidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Umidade3table)
                                    .addComponent(Umidade2table)
                                    .addComponent(Umidade1table, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Cinzas1table)
                                    .addComponent(Cinzas2table)
                                    .addComponent(jTextField6)
                                    .addComponent(btnCinzas, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(104, 104, 104)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Proteinas1table, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Proteinas2table, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnProteinas, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnLipidios, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                        .addComponent(Lipidios1table))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField12, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Lipidios2table, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)))
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Fibras1table)
                                    .addComponent(btnFibras, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                    .addComponent(Fibras2table)
                                    .addComponent(jTextField4))
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCarboidratos, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Carboidratos2table, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Carboidratos1table, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(442, 442, 442))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane6))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InserirAmostra1)
                .addGap(413, 413, 413))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUmidade)
                            .addComponent(btnCinzas)
                            .addComponent(btnProteinas)
                            .addComponent(btnLipidios)
                            .addComponent(btnFibras))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Umidade1table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cinzas1table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Proteinas1table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lipidios1table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fibras1table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Umidade2table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cinzas2table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Proteinas2table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lipidios2table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fibras2table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Umidade3table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCarboidratos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Carboidratos1table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Carboidratos2table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(InserirAmostra1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(InserirAmostra2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(InserirAmostra3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFibrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFibrasActionPerformed
        // TODO add your handling code here:
        Fibras frame = new Fibras (this,true);
        frame.setVisible(true);
    }//GEN-LAST:event_btnFibrasActionPerformed

    private void btnUmidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUmidadeActionPerformed
        // TODO add your handling code here:
        Umidade frame = new Umidade(this,true);
        frame.setVisible(true);
        
        this.Umidade1table.setText(String.valueOf(this.umid.getInserir1()));
        this.Umidade2table.setText(String.valueOf(this.umid.getInserir2()));
        this.Umidade3table.setText (String.valueOf(this.umid.getInserir3()));
    }//GEN-LAST:event_btnUmidadeActionPerformed

    private void btnCinzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCinzasActionPerformed
        // TODO add your handling code here:
        Cinzas frame = new Cinzas (this,true);
        frame.setVisible(true);
    }//GEN-LAST:event_btnCinzasActionPerformed

    private void btnProteinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProteinasActionPerformed
        // TODO add your handling code here:
        Proteinas frame = new Proteinas (this,true);
        frame.setVisible(true);
    }//GEN-LAST:event_btnProteinasActionPerformed

    private void btnCarboidratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarboidratosActionPerformed
        // TODO add your handling code here:
        Carboidratos frame = new Carboidratos (this, true);
        frame.setVisible(true);
    }//GEN-LAST:event_btnCarboidratosActionPerformed

    private void btnLipidiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLipidiosActionPerformed
        // TODO add your handling code here:
        Lipidios frame = new Lipidios (this, true);
        frame.setVisible(true);
    }//GEN-LAST:event_btnLipidiosActionPerformed

    private void Umidade1tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Umidade1tableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Umidade1tableActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void InserirAmostra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirAmostra1ActionPerformed
       DefaultTableModel dtm = (DefaultTableModel) amostra1.getModel();
       dtm.addRow(new Object[]{Umidade1table.getText(), Cinzas1table.getText(), Proteinas1table.getText(), Lipidios1table.getText(), Fibras1table.getText(), Carboidratos1table.getText()});
    }//GEN-LAST:event_InserirAmostra1ActionPerformed

    private void InserirAmostra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirAmostra2ActionPerformed
       DefaultTableModel dtm = (DefaultTableModel) amostra2.getModel();
       dtm.addRow(new Object[]{Umidade2table.getText(), Cinzas2table.getText(), Proteinas2table.getText(), Lipidios2table.getText(), Fibras2table.getText(), Carboidratos2table.getText()});
    }//GEN-LAST:event_InserirAmostra2ActionPerformed

    private void Fibras2tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fibras2tableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Fibras2tableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Carboidratos1table;
    private javax.swing.JTextField Carboidratos2table;
    public static javax.swing.JTextField Cinzas1table;
    private javax.swing.JTextField Cinzas2table;
    private javax.swing.JTextField Fibras1table;
    private javax.swing.JTextField Fibras2table;
    private javax.swing.JButton InserirAmostra1;
    private javax.swing.JButton InserirAmostra2;
    private javax.swing.JButton InserirAmostra3;
    private javax.swing.JTextField Lipidios1table;
    private javax.swing.JTextField Lipidios2table;
    private javax.swing.JTextField Proteinas1table;
    private javax.swing.JTextField Proteinas2table;
    public static javax.swing.JTextField Umidade1table;
    private javax.swing.JTextField Umidade2table;
    private javax.swing.JTextField Umidade3table;
    private javax.swing.JTable amostra1;
    private javax.swing.JTable amostra2;
    private javax.swing.JTable amostra3;
    private javax.swing.JButton btnCarboidratos;
    private javax.swing.JButton btnCinzas;
    private javax.swing.JButton btnFibras;
    private javax.swing.JButton btnLipidios;
    private javax.swing.JButton btnProteinas;
    private javax.swing.JButton btnUmidade;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

    public void recebeUmidade (String resultado1 ){
        
    }
}
