/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bkp;

/**
 *
 * @author alves
 */
public class Carboidratos extends javax.swing.JDialog {

    /**
     * Creates new form Carboidratos
     */
    public Carboidratos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel65 = new javax.swing.JLabel();
        txtCalcularCar = new javax.swing.JTextField();
        btnCalcularCar = new javax.swing.JButton();
        txtMediaCar = new javax.swing.JTextField();
        jButton20 = new javax.swing.JButton();
        txtCalcularCar2 = new javax.swing.JTextField();
        btnCalcularCar2 = new javax.swing.JButton();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        txtProteinasCar = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        txtFibrasCar = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        txtLipidiosCar = new javax.swing.JTextField();
        btnInserirCarboidratos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtUmidadeCar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCinzasCar = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        txtProteinas2Car = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        txtFibras2Car = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        txtLipidios2Car = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUmidade2Car = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCinzas2Car = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        txtProteinas3Car = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        txtFibras3Car = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        txtLipidios3Car = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtUmidade3Car = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCinzas3Car = new javax.swing.JTextField();
        txtCalcularCar3 = new javax.swing.JTextField();
        btnCalcularCar3 = new javax.swing.JButton();
        btnDesvioPadraoUmidade = new javax.swing.JButton();
        txtDesvioPadraoCarboidratos = new javax.swing.JTextField();
        btnvarianciacar = new javax.swing.JButton();
        txtvarianciaCar = new javax.swing.JTextField();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CALCEN");

        jLabel65.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel65.setText("Amostra 2:");

        btnCalcularCar.setText("Calcular:");
        btnCalcularCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularCarActionPerformed(evt);
            }
        });

        jButton20.setText("Média");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        btnCalcularCar2.setText("Calcular:");
        btnCalcularCar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularCar2ActionPerformed(evt);
            }
        });

        jLabel59.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(0, 0, 0));
        jLabel59.setText("Carboidratos");

        jLabel60.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel60.setText("Amostra 1:");

        jLabel61.setText("Proteinas");

        txtProteinasCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProteinasCarActionPerformed(evt);
            }
        });

        jLabel62.setText("Fibras");

        jLabel63.setText("Lipidios");

        jLabel53.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel53.setText("Amostra 3:");

        btnInserirCarboidratos.setText("Inserir");
        btnInserirCarboidratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirCarboidratosActionPerformed(evt);
            }
        });

        jLabel1.setText("Umidade");

        txtUmidadeCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUmidadeCarActionPerformed(evt);
            }
        });

        jLabel2.setText("Cinzas");

        txtCinzasCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCinzasCarActionPerformed(evt);
            }
        });

        jLabel66.setText("Proteinas");

        txtProteinas2Car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProteinas2CarActionPerformed(evt);
            }
        });

        jLabel67.setText("Fibras");

        jLabel68.setText("Lipidios");

        jLabel3.setText("Umidade");

        txtUmidade2Car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUmidade2CarActionPerformed(evt);
            }
        });

        jLabel4.setText("Cinzas");

        txtCinzas2Car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCinzas2CarActionPerformed(evt);
            }
        });

        jLabel69.setText("Proteinas");

        txtProteinas3Car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProteinas3CarActionPerformed(evt);
            }
        });

        jLabel70.setText("Fibras");

        jLabel71.setText("Lipidios");

        jLabel5.setText("Umidade");

        txtUmidade3Car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUmidade3CarActionPerformed(evt);
            }
        });

        jLabel6.setText("Cinzas");

        txtCinzas3Car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCinzas3CarActionPerformed(evt);
            }
        });

        btnCalcularCar3.setText("Calcular:");
        btnCalcularCar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularCar3ActionPerformed(evt);
            }
        });

        btnDesvioPadraoUmidade.setText("Desvio Padrão");
        btnDesvioPadraoUmidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesvioPadraoUmidadeActionPerformed(evt);
            }
        });

        btnvarianciacar.setText("Variância");
        btnvarianciacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvarianciacarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel60)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel61)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtProteinasCar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel62)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtFibrasCar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel63)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtLipidiosCar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtUmidadeCar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCinzasCar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCalcularCar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCalcularCar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(355, 355, 355)
                            .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel66)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtProteinas2Car, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel67)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtFibras2Car, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel68)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtLipidios2Car, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtUmidade2Car, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtCinzas2Car, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel69)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtProteinas3Car, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel70)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtFibras3Car, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel71)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtLipidios3Car, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtUmidade3Car, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtCinzas3Car, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel53))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnCalcularCar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCalcularCar3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCalcularCar2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCalcularCar3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel65))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(btnvarianciacar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMediaCar, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(txtvarianciaCar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnInserirCarboidratos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDesvioPadraoUmidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDesvioPadraoCarboidratos, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel60)
                            .addGap(33, 33, 33))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProteinasCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel61)
                            .addComponent(jLabel62)
                            .addComponent(txtFibrasCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel63)
                            .addComponent(txtLipidiosCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUmidadeCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txtCinzasCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCalcularCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCalcularCar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel65)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcularCar2)
                    .addComponent(txtCalcularCar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProteinas2Car, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel66)
                    .addComponent(jLabel67)
                    .addComponent(txtFibras2Car, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel68)
                    .addComponent(txtLipidios2Car, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUmidade2Car, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtCinzas2Car, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(13, 13, 13)
                .addComponent(jLabel53)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProteinas3Car, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel69)
                    .addComponent(jLabel70)
                    .addComponent(txtFibras3Car, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel71)
                    .addComponent(txtLipidios3Car, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUmidade3Car, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtCinzas3Car, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnCalcularCar3)
                    .addComponent(txtCalcularCar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDesvioPadraoCarboidratos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDesvioPadraoUmidade)
                    .addComponent(jButton20)
                    .addComponent(txtMediaCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserirCarboidratos)
                    .addComponent(btnvarianciacar)
                    .addComponent(txtvarianciaCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        double resultcar, resultcar2, resultcar3, mediacarboidratos;

        resultcar = Double.parseDouble(txtCalcularCar.getText());
        resultcar2 = Double.parseDouble(txtCalcularCar2.getText());
        resultcar3 = Double.parseDouble(txtCalcularCar3.getText());

        mediacarboidratos = (resultcar + resultcar2 + resultcar3) / 3;

        txtMediaCar.setText(String.valueOf(mediacarboidratos));
    }//GEN-LAST:event_jButton20ActionPerformed

    private void btnInserirCarboidratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirCarboidratosActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_btnInserirCarboidratosActionPerformed

    private void txtProteinasCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProteinasCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProteinasCarActionPerformed

    private void txtUmidadeCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUmidadeCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUmidadeCarActionPerformed

    private void txtCinzasCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCinzasCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCinzasCarActionPerformed

    private void txtProteinas2CarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProteinas2CarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProteinas2CarActionPerformed

    private void txtUmidade2CarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUmidade2CarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUmidade2CarActionPerformed

    private void txtCinzas2CarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCinzas2CarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCinzas2CarActionPerformed

    private void txtProteinas3CarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProteinas3CarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProteinas3CarActionPerformed

    private void txtUmidade3CarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUmidade3CarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUmidade3CarActionPerformed

    private void txtCinzas3CarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCinzas3CarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCinzas3CarActionPerformed

    private void btnCalcularCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularCarActionPerformed
        // TODO add your handling code here:
        double vca1, vca2, vca3, vca4, vca5, resultcar1;

        vca1 = Double.parseDouble (txtProteinasCar.getText());
        vca2 = Double.parseDouble(txtFibrasCar.getText());
        vca3 = Double.parseDouble(txtLipidiosCar.getText());
        vca4 = Double.parseDouble (txtUmidadeCar.getText());
        vca5 = Double.parseDouble(txtCinzasCar.getText());

        resultcar1 = 100 - (vca1 + vca2 + vca3 + vca4 + vca5);

        txtCalcularCar.setText(String.valueOf(resultcar1));
    }//GEN-LAST:event_btnCalcularCarActionPerformed

    private void btnCalcularCar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularCar2ActionPerformed
        // TODO add your handling code here:
        double vca1, vca2, vca3, vca4, vca5, resultcar2;

        vca1 = Double.parseDouble (txtProteinas2Car.getText());
        vca2 = Double.parseDouble(txtFibras2Car.getText());
        vca3 = Double.parseDouble(txtLipidios2Car.getText());
        vca4 = Double.parseDouble (txtUmidade2Car.getText());
        vca5 = Double.parseDouble(txtCinzas2Car.getText());

        resultcar2 = 100 - (vca1 + vca2 + vca3 + vca4 + vca5);

        txtCalcularCar.setText(String.valueOf(resultcar2));
    }//GEN-LAST:event_btnCalcularCar2ActionPerformed

    private void btnCalcularCar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularCar3ActionPerformed
        // TODO add your handling code here:
        double vca1, vca2, vca3, vca4, vca5, resultcar3;

        vca1 = Double.parseDouble (txtProteinas3Car.getText());
        vca2 = Double.parseDouble(txtFibras3Car.getText());
        vca3 = Double.parseDouble(txtLipidios3Car.getText());
        vca4 = Double.parseDouble (txtUmidade3Car.getText());
        vca5 = Double.parseDouble(txtCinzas3Car.getText());

        resultcar3 = 100 - (vca1 + vca2 + vca3 + vca4 + vca5);

        txtCalcularCar.setText(String.valueOf(resultcar3));
    }//GEN-LAST:event_btnCalcularCar3ActionPerformed

    private void btnDesvioPadraoUmidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesvioPadraoUmidadeActionPerformed
        // TODO add your handling code here:
        double vca1, vca2, vca3,vca4,vca5, somatorioCar1, somatorioCar2, somatorioCar3,varianciaCar;
        double resultcar, resultcar2, resultcar3, mediacarboidratos;
        
        resultcar = Double.parseDouble(txtCalcularCar.getText());
        resultcar2 = Double.parseDouble(txtCalcularCar3.getText());
        resultcar3 = Double.parseDouble (txtProteinas3Car.getText());
        
        mediacarboidratos = (resultcar + resultcar2 + resultcar3) / 3;     
        
        vca1 = Double.parseDouble (txtCalcularCar.getText());
        vca2 = Double.parseDouble(txtCalcularCar2.getText());
        vca3 = Double.parseDouble(txtCalcularCar3.getText());
        
        somatorioCar1 = Math.pow((vca1-mediacarboidratos),2);     
        somatorioCar2 = Math.pow((vca2-mediacarboidratos),2);
        somatorioCar3 = Math.pow((vca3-mediacarboidratos),2);
        
        varianciaCar = somatorioCar1+somatorioCar2+somatorioCar3/5;
        txtvarianciaCar.setText(String.valueOf(varianciaCar));
    }//GEN-LAST:event_btnDesvioPadraoUmidadeActionPerformed

    private void btnvarianciacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvarianciacarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnvarianciacarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carboidratos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carboidratos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carboidratos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carboidratos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Carboidratos dialog = new Carboidratos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularCar;
    private javax.swing.JButton btnCalcularCar2;
    private javax.swing.JButton btnCalcularCar3;
    private javax.swing.JButton btnDesvioPadraoUmidade;
    private javax.swing.JButton btnInserirCarboidratos;
    private javax.swing.JButton btnvarianciacar;
    private javax.swing.JButton jButton20;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JTextField txtCalcularCar;
    private javax.swing.JTextField txtCalcularCar2;
    private javax.swing.JTextField txtCalcularCar3;
    private javax.swing.JTextField txtCinzas2Car;
    private javax.swing.JTextField txtCinzas3Car;
    private javax.swing.JTextField txtCinzasCar;
    private javax.swing.JTextField txtDesvioPadraoCarboidratos;
    private javax.swing.JTextField txtFibras2Car;
    private javax.swing.JTextField txtFibras3Car;
    private javax.swing.JTextField txtFibrasCar;
    private javax.swing.JTextField txtLipidios2Car;
    private javax.swing.JTextField txtLipidios3Car;
    private javax.swing.JTextField txtLipidiosCar;
    private javax.swing.JTextField txtMediaCar;
    private javax.swing.JTextField txtProteinas2Car;
    private javax.swing.JTextField txtProteinas3Car;
    private javax.swing.JTextField txtProteinasCar;
    private javax.swing.JTextField txtUmidade2Car;
    private javax.swing.JTextField txtUmidade3Car;
    private javax.swing.JTextField txtUmidadeCar;
    private javax.swing.JTextField txtvarianciaCar;
    // End of variables declaration//GEN-END:variables
}
