/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bkp;

/**
 *
 * @author alves
 */
public class Fibras extends javax.swing.JDialog {

    /**
     * Creates new form Fibras
     */
    public Fibras(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtfinalfi3 = new javax.swing.JTextField();
        btncalcularfi2 = new javax.swing.JButton();
        txtmediafibras = new javax.swing.JTextField();
        btncalcularfi1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtinicial2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtcalcularfi3 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txtamostrafi2 = new javax.swing.JTextField();
        txtinicial1 = new javax.swing.JTextField();
        btnmediafibras = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtamostrafi1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtfinalfi2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtresultadofi3 = new javax.swing.JTextField();
        txtfinalfi1 = new javax.swing.JTextField();
        txtinicial3 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtresultadofi2 = new javax.swing.JTextField();
        txtresultadofi1 = new javax.swing.JTextField();
        txtamostrafi3 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        btnInserirFibras = new javax.swing.JButton();
        btnDesvioPadraoUmidade = new javax.swing.JButton();
        txtDesvioPadraoCinzas = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CALCEN");

        btncalcularfi2.setText("Calcular:");
        btncalcularfi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularfi2ActionPerformed(evt);
            }
        });

        txtmediafibras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmediafibrasActionPerformed(evt);
            }
        });

        btncalcularfi1.setText("Calcular:");
        btncalcularfi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularfi1ActionPerformed(evt);
            }
        });

        jLabel7.setText("P. Cadinho Vazio");

        txtinicial2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinicial2ActionPerformed(evt);
            }
        });

        jLabel20.setText("P. Amostra");

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel21.setText("Amostra 1:");

        txtcalcularfi3.setText("Calcular:");
        txtcalcularfi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcalcularfi3ActionPerformed(evt);
            }
        });

        jLabel22.setText("P. Cadinho Vazio");

        txtinicial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinicial1ActionPerformed(evt);
            }
        });

        btnmediafibras.setText("Média");
        btnmediafibras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmediafibrasActionPerformed(evt);
            }
        });

        jLabel25.setText("P. Final");

        jLabel23.setText("P. Amostra");

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel16.setText("Amostra 3:");

        txtfinalfi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfinalfi2ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel26.setText("Fibras");

        jLabel24.setText("P. Final");

        jLabel17.setText("P. Cadinho Vazio");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setText("Amostra 2:");

        txtresultadofi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtresultadofi3ActionPerformed(evt);
            }
        });

        txtinicial3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinicial3ActionPerformed(evt);
            }
        });

        jLabel18.setText("P. Amostra");

        jLabel19.setText("P. Final");

        btnInserirFibras.setText("Inserir");
        btnInserirFibras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirFibrasActionPerformed(evt);
            }
        });

        btnDesvioPadraoUmidade.setText("Desvio Padrão");
        btnDesvioPadraoUmidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesvioPadraoUmidadeActionPerformed(evt);
            }
        });

        jButton1.setText("Variância");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel16)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtinicial2))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtinicial3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel22)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtinicial1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtamostrafi2))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtamostrafi3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel23)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtamostrafi1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtfinalfi3))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel25)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtfinalfi2))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel24)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtfinalfi1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel21))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(txtcalcularfi3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtresultadofi3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btncalcularfi1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtresultadofi1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btncalcularfi2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtresultadofi2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(325, 325, 325)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnmediafibras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmediafibras)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDesvioPadraoUmidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDesvioPadraoCinzas, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnInserirFibras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel26)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtinicial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22)
                                .addComponent(jLabel23)
                                .addComponent(txtamostrafi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel24)
                                .addComponent(txtfinalfi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btncalcularfi1)
                                .addComponent(txtresultadofi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(txtamostrafi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25)
                                    .addComponent(txtfinalfi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btncalcularfi2)
                                    .addComponent(txtresultadofi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel21)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtinicial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(33, 33, 33))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtinicial3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17)
                                .addComponent(jLabel18)
                                .addComponent(txtamostrafi3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19)
                                .addComponent(txtfinalfi3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtcalcularfi3)
                                .addComponent(txtresultadofi3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDesvioPadraoCinzas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDesvioPadraoUmidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInserirFibras))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnmediafibras)
                            .addComponent(txtmediafibras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncalcularfi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularfi2ActionPerformed
        // TODO add your handling code here:
        double vf1, vf2, vf3, resultfi2, mediafi2;

        vf1 = Double.parseDouble (txtinicial2.getText());
        vf2 = Double.parseDouble(txtamostrafi2.getText());
        vf3 = Double.parseDouble(txtfinalfi2.getText());

        resultfi2 = ((vf1-vf3)*100) / vf2;

        txtresultadofi2.setText(String.valueOf(resultfi2));
    }//GEN-LAST:event_btncalcularfi2ActionPerformed

    private void txtmediafibrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmediafibrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmediafibrasActionPerformed

    private void btncalcularfi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularfi1ActionPerformed
        // TODO add your handling code here:
        double vf1, vf2, vf3, resultfi, mediafi;

        vf1 = Double.parseDouble (txtinicial1.getText());
        vf2 = Double.parseDouble(txtamostrafi1.getText());
        vf3 = Double.parseDouble(txtfinalfi1.getText());

        resultfi = ((vf1-vf3)*100) / vf2;

        txtresultadofi1.setText(String.valueOf(resultfi));
    }//GEN-LAST:event_btncalcularfi1ActionPerformed

    private void txtinicial2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinicial2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinicial2ActionPerformed

    private void txtcalcularfi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcalcularfi3ActionPerformed
        // TODO add your handling code here:
        double vf1, vf2, vf3, resultcin3, mediacin3;

        vf1 = Double.parseDouble (txtinicial3.getText());
        vf2 = Double.parseDouble(txtamostrafi3.getText());
        vf3 = Double.parseDouble(txtfinalfi3.getText());

        resultcin3 = ((vf1-vf3)*100) / vf2;

        txtresultadofi3.setText(String.valueOf(resultcin3));
    }//GEN-LAST:event_txtcalcularfi3ActionPerformed

    private void txtinicial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinicial1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinicial1ActionPerformed

    private void btnmediafibrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmediafibrasActionPerformed
        // TODO add your handling code here:
        double resultfi, resultfi2, resultfi3, mediafibras;

        resultfi = Double.parseDouble(txtresultadofi1.getText());
        resultfi2 = Double.parseDouble(txtresultadofi2.getText());
        resultfi3 = Double.parseDouble(txtresultadofi3.getText());

        mediafibras = (resultfi + resultfi2 + resultfi3) / 3;

        txtmediafibras.setText(String.valueOf(mediafibras));
    }//GEN-LAST:event_btnmediafibrasActionPerformed

    private void txtfinalfi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfinalfi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfinalfi2ActionPerformed

    private void txtresultadofi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtresultadofi3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtresultadofi3ActionPerformed

    private void txtinicial3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinicial3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinicial3ActionPerformed

    private void btnInserirFibrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirFibrasActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_btnInserirFibrasActionPerformed

    private void btnDesvioPadraoUmidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesvioPadraoUmidadeActionPerformed
        double n1, n2, n3, somatoriocin, variancafi, despadraofi;
        double resultfi, resultfi2, resultfi3, mediafibras;

        n1 = Double.parseDouble (txtresultadofi1.getText());
        n2 = Double.parseDouble(txtresultadofi2.getText());
        n3 = Double.parseDouble(txtresultadofi3.getText());
        somatoriocin = (Math.pow(n1,2)) + (Math.pow(n2,2)) + (Math.pow(n3, 2));

        resultfi = Double.parseDouble(txtresultadofi1.getText());
        resultfi2 = Double.parseDouble(txtresultadofi2.getText());
        resultfi3 = Double.parseDouble(txtresultadofi3.getText());
        mediafibras = (resultfi + resultfi + resultfi3) / 3;

        variancafi = somatoriocin - 3 * Math.pow(mediafibras,2) / 3 - 1;
        despadraofi = Math.sqrt (variancafi);
        txtDesvioPadraoCinzas.setText(String.valueOf(despadraofi));
    }//GEN-LAST:event_btnDesvioPadraoUmidadeActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fibras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fibras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fibras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fibras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Fibras dialog = new Fibras(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesvioPadraoUmidade;
    private javax.swing.JButton btnInserirFibras;
    private javax.swing.JButton btncalcularfi1;
    private javax.swing.JButton btncalcularfi2;
    private javax.swing.JButton btnmediafibras;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtDesvioPadraoCinzas;
    private javax.swing.JTextField txtamostrafi1;
    private javax.swing.JTextField txtamostrafi2;
    private javax.swing.JTextField txtamostrafi3;
    private javax.swing.JButton txtcalcularfi3;
    private javax.swing.JTextField txtfinalfi1;
    private javax.swing.JTextField txtfinalfi2;
    private javax.swing.JTextField txtfinalfi3;
    private javax.swing.JTextField txtinicial1;
    private javax.swing.JTextField txtinicial2;
    private javax.swing.JTextField txtinicial3;
    private javax.swing.JTextField txtmediafibras;
    private javax.swing.JTextField txtresultadofi1;
    private javax.swing.JTextField txtresultadofi2;
    private javax.swing.JTextField txtresultadofi3;
    // End of variables declaration//GEN-END:variables
}
