/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bkp;

/**
 *
 * @author alves
 */
public class Lipidios extends javax.swing.JDialog {

    /**
     * Creates new form Lipidios
     */
    public Lipidios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtcadinholip1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtamostralip1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtfinallip1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txtamostralip2 = new javax.swing.JTextField();
        txtcadinholip3 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtfinallip2 = new javax.swing.JTextField();
        txtamostralip3 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtresultadolip3 = new javax.swing.JTextField();
        txtfinallip3 = new javax.swing.JTextField();
        btnlipidios3 = new javax.swing.JButton();
        txtmedialip = new javax.swing.JTextField();
        btnmedialip = new javax.swing.JButton();
        txtresultadolip1 = new javax.swing.JTextField();
        btnlipidios1 = new javax.swing.JButton();
        txtresultadolip2 = new javax.swing.JTextField();
        btnlipidios2 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        txtcandinholip2 = new javax.swing.JTextField();
        btnInserirLipidios = new javax.swing.JButton();
        btnDesvioPadraoUmidade = new javax.swing.JButton();
        txtDesvioPadraoLipidios = new javax.swing.JTextField();
        btnVariancialip = new javax.swing.JButton();
        txtvariancialip = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CALCEN");

        jLabel28.setText("P. Amostra");

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel29.setText("Lipídios");

        jLabel30.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel30.setText("Amostra 1:");

        jLabel31.setText("P. Cadinho Vazio");

        txtcadinholip1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcadinholip1ActionPerformed(evt);
            }
        });

        jLabel32.setText("P. Amostra");

        jLabel33.setText("P. Final");

        jLabel36.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel36.setText("Amostra 3:");

        txtfinallip1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfinallip1ActionPerformed(evt);
            }
        });

        jLabel37.setText("P. Cadinho Vazio");

        txtamostralip2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtamostralip2ActionPerformed(evt);
            }
        });

        txtcadinholip3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcadinholip3ActionPerformed(evt);
            }
        });

        jLabel38.setText("P. Amostra");

        jLabel34.setText("P. Final");

        jLabel35.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel35.setText("Amostra 2:");

        jLabel39.setText("P. Final");

        txtresultadolip3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtresultadolip3ActionPerformed(evt);
            }
        });

        btnlipidios3.setText("Calcular:");
        btnlipidios3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlipidios3ActionPerformed(evt);
            }
        });

        btnmedialip.setText("Média");
        btnmedialip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmedialipActionPerformed(evt);
            }
        });

        btnlipidios1.setText("Calcular:");
        btnlipidios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlipidios1ActionPerformed(evt);
            }
        });

        btnlipidios2.setText("Calcular:");
        btnlipidios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlipidios2ActionPerformed(evt);
            }
        });

        jLabel27.setText("P. Cadinho Vazio");

        txtcandinholip2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcandinholip2ActionPerformed(evt);
            }
        });

        btnInserirLipidios.setText("Inserir");
        btnInserirLipidios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirLipidiosActionPerformed(evt);
            }
        });

        btnDesvioPadraoUmidade.setText("Desvio Padrão");
        btnDesvioPadraoUmidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesvioPadraoUmidadeActionPerformed(evt);
            }
        });

        btnVariancialip.setText("Variância");
        btnVariancialip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVariancialipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel30))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel31)
                            .addGap(6, 6, 6)
                            .addComponent(txtcadinholip1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel32))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel37)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtcadinholip3))
                                .addComponent(jLabel35)
                                .addComponent(jLabel36)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel27)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtcandinholip2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel38)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtamostralip3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel39)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtfinallip3))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtamostralip1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(jLabel28)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtamostralip2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel34)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtfinallip2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(153, 153, 153)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addComponent(jLabel33)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtfinallip1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnlipidios2)
                                        .addComponent(btnlipidios3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtresultadolip2, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                        .addComponent(txtresultadolip3)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnlipidios1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtresultadolip1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnmedialip, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(btnVariancialip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmedialip, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(txtvariancialip))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInserirLipidios, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDesvioPadraoUmidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDesvioPadraoLipidios, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(33, 33, 33))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtcadinholip1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtresultadolip1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnlipidios1)
                                .addComponent(jLabel31)
                                .addComponent(jLabel32)
                                .addComponent(txtamostralip1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel33)))
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txtcandinholip2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtresultadolip2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)
                            .addComponent(txtamostralip2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34)
                            .addComponent(txtfinallip2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnlipidios2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addGap(33, 33, 33))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtcadinholip3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnlipidios3)
                                .addComponent(jLabel37)
                                .addComponent(txtresultadolip3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel38)
                                .addComponent(txtamostralip3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel39)
                                .addComponent(txtfinallip3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtfinallip1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnmedialip)
                        .addComponent(txtmedialip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDesvioPadraoUmidade)
                        .addComponent(txtDesvioPadraoLipidios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserirLipidios)
                    .addComponent(btnVariancialip)
                    .addComponent(txtvariancialip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcadinholip1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcadinholip1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcadinholip1ActionPerformed

    private void txtfinallip1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfinallip1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfinallip1ActionPerformed

    private void txtamostralip2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtamostralip2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtamostralip2ActionPerformed

    private void txtcadinholip3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcadinholip3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcadinholip3ActionPerformed

    private void txtresultadolip3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtresultadolip3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtresultadolip3ActionPerformed

    private void btnlipidios3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlipidios3ActionPerformed
        // TODO add your handling code here:
        double v1, v2, v3, result3;

        v1 = Double.parseDouble (txtcadinholip3.getText());
        v2 = Double.parseDouble(txtamostralip3.getText());
        v3 = Double.parseDouble(txtfinallip3.getText());

        result3 = (((v3-v1)*4)/v2)*100;

        txtresultadolip3.setText(String.valueOf(result3));
    }//GEN-LAST:event_btnlipidios3ActionPerformed

    private void btnmedialipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmedialipActionPerformed
        // TODO add your handling code here:
        double resultlip, resultlip2, resultlip3, medialipidios;

        resultlip = Double.parseDouble(txtresultadolip1.getText());
        resultlip2 = Double.parseDouble(txtresultadolip2.getText());
        resultlip3 = Double.parseDouble(txtresultadolip3.getText());

        medialipidios = (resultlip + resultlip2 + resultlip3) / 3;

        txtmedialip.setText(String.valueOf(medialipidios));
    }//GEN-LAST:event_btnmedialipActionPerformed

    private void btnlipidios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlipidios1ActionPerformed
        // TODO add your handling code here:
        double v1, v2, v3, result;

        v1 = Double.parseDouble (txtcadinholip1.getText());
        v2 = Double.parseDouble(txtamostralip1.getText());
        v3 = Double.parseDouble(txtfinallip1.getText());

        result = (((v3-v1)*4)/v2)*100;

        txtresultadolip1.setText(String.valueOf(result));
    }//GEN-LAST:event_btnlipidios1ActionPerformed

    private void btnlipidios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlipidios2ActionPerformed
        // TODO add your handling code here:
        double v1, v2, v3, result2;

        v1 = Double.parseDouble (txtcandinholip2.getText());
        v2 = Double.parseDouble(txtamostralip2.getText());
        v3 = Double.parseDouble(txtfinallip2.getText());

        result2 = (((v3-v1)*4)/v2)*100;

        txtresultadolip2.setText(String.valueOf(result2));
    }//GEN-LAST:event_btnlipidios2ActionPerformed

    private void txtcandinholip2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcandinholip2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcandinholip2ActionPerformed

    private void btnInserirLipidiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirLipidiosActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_btnInserirLipidiosActionPerformed

    private void btnDesvioPadraoUmidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesvioPadraoUmidadeActionPerformed
        double n1, n2, n3, somatoriolip1, somatoriolip2, somatoriolip3, variancialip, despadraolip;
        double resultlip, resultlip2, resultlip3, medialipidios;
        
        resultlip = Double.parseDouble(txtresultadolip1.getText());
        resultlip2 = Double.parseDouble(txtresultadolip2.getText());
        resultlip3 = Double.parseDouble(txtresultadolip3.getText());
        medialipidios = (resultlip + resultlip2 + resultlip3) / 3;
        
        n1 = Double.parseDouble (txtresultadolip1.getText());
        n2 = Double.parseDouble(txtresultadolip2.getText());
        n3 = Double.parseDouble(txtresultadolip3.getText());
        somatoriolip1 = Math.pow(n1-medialipidios,2);     
        somatoriolip2 = Math.pow(n2-medialipidios,2);
        somatoriolip3 = Math.pow(n3-medialipidios,2);


        variancialip= somatoriolip1+somatoriolip2+somatoriolip3/3;
        
        despadraolip= Math.sqrt(variancialip);
       
        txtDesvioPadraoLipidios.setText(String.valueOf(despadraolip));
    }//GEN-LAST:event_btnDesvioPadraoUmidadeActionPerformed

    private void btnVariancialipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVariancialipActionPerformed
        // TODO add your handling code here:
        double n1, n2, n3, somatoriolip1, somatoriolip2, somatoriolip3, variancialip;
        double resultlip, resultlip2, resultlip3, medialipidios;
        
        resultlip = Double.parseDouble(txtresultadolip1.getText());
        resultlip2 = Double.parseDouble(txtresultadolip2.getText());
        resultlip3 = Double.parseDouble(txtresultadolip3.getText());
        medialipidios = (resultlip + resultlip2 + resultlip3) / 3;
        
        n1 = Double.parseDouble (txtresultadolip1.getText());
        n2 = Double.parseDouble(txtresultadolip2.getText());
        n3 = Double.parseDouble(txtresultadolip3.getText());
        somatoriolip1 = Math.pow(n1-medialipidios,2);     
        somatoriolip2 = Math.pow(n2-medialipidios,2);
        somatoriolip3 = Math.pow(n3-medialipidios,2);


        variancialip= somatoriolip1+somatoriolip2+somatoriolip3/3;
        txtvariancialip.setText(String.valueOf(variancialip));
    }//GEN-LAST:event_btnVariancialipActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lipidios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lipidios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lipidios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lipidios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Lipidios dialog = new Lipidios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesvioPadraoUmidade;
    private javax.swing.JButton btnInserirLipidios;
    private javax.swing.JButton btnVariancialip;
    private javax.swing.JButton btnlipidios1;
    private javax.swing.JButton btnlipidios2;
    private javax.swing.JButton btnlipidios3;
    private javax.swing.JButton btnmedialip;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JTextField txtDesvioPadraoLipidios;
    private javax.swing.JTextField txtamostralip1;
    private javax.swing.JTextField txtamostralip2;
    private javax.swing.JTextField txtamostralip3;
    private javax.swing.JTextField txtcadinholip1;
    private javax.swing.JTextField txtcadinholip3;
    private javax.swing.JTextField txtcandinholip2;
    private javax.swing.JTextField txtfinallip1;
    private javax.swing.JTextField txtfinallip2;
    private javax.swing.JTextField txtfinallip3;
    private javax.swing.JTextField txtmedialip;
    private javax.swing.JTextField txtresultadolip1;
    private javax.swing.JTextField txtresultadolip2;
    private javax.swing.JTextField txtresultadolip3;
    private javax.swing.JTextField txtvariancialip;
    // End of variables declaration//GEN-END:variables
}
