/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bkp;

/**
 *
 * @author alves
 */
public class Proteinas extends javax.swing.JDialog {

    /**
     * Creates new form Proteinas
     */
    public Proteinas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel41 = new javax.swing.JLabel();
        btnCalcularprot3 = new javax.swing.JButton();
        btnMediaProt = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        txtPAmostra3 = new javax.swing.JTextField();
        txtVolume3 = new javax.swing.JTextField();
        btnCalcularprot1 = new javax.swing.JButton();
        txtMediaProt = new javax.swing.JTextField();
        btnCalcularprot2 = new javax.swing.JButton();
        txtPAmostra1 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        txtFatorConexao = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        txtVolume = new javax.swing.JTextField();
        txtFatorConexao2 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        txtVolume2 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txtFatorConexao3 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtPAmostra2 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        txtCalcularProt1 = new javax.swing.JTextField();
        txtCalcularProt2 = new javax.swing.JTextField();
        txtCalcularProt3 = new javax.swing.JTextField();
        btnInserirProteinas = new javax.swing.JButton();
        btnDesvioPadraoProteinas = new javax.swing.JButton();
        txtDesvioPadraoProteinas = new javax.swing.JTextField();
        btnvarianciaprot = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CALCEN");

        jLabel41.setText("Volume");

        btnCalcularprot3.setText("Calcular:");
        btnCalcularprot3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularprot3ActionPerformed(evt);
            }
        });

        btnMediaProt.setText("Média");
        btnMediaProt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediaProtActionPerformed(evt);
            }
        });

        jLabel51.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel51.setText("Amostra 3:");

        jLabel52.setText("P.  Amostra");

        txtPAmostra3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPAmostra3ActionPerformed(evt);
            }
        });

        btnCalcularprot1.setText("Calcular:");
        btnCalcularprot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularprot1ActionPerformed(evt);
            }
        });

        btnCalcularprot2.setText("Calcular:");
        btnCalcularprot2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularprot2ActionPerformed(evt);
            }
        });

        txtPAmostra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPAmostra1ActionPerformed(evt);
            }
        });

        jLabel46.setText("Fator de Conexão");

        jLabel47.setText("Volume");

        jLabel48.setText("Volume");

        jLabel49.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel49.setText("Proteínas");

        jLabel50.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel50.setText("Amostra 2:");

        jLabel40.setText("Fator de Conexão");

        jLabel42.setText("P.  Amostra");

        txtPAmostra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPAmostra2ActionPerformed(evt);
            }
        });

        jLabel43.setText("Fator de Conexão");

        jLabel44.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel44.setText("Amostra 1:");

        jLabel45.setText("P.  Amostra");

        txtCalcularProt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCalcularProt1ActionPerformed(evt);
            }
        });

        btnInserirProteinas.setText("Inserir");
        btnInserirProteinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirProteinasActionPerformed(evt);
            }
        });

        btnDesvioPadraoProteinas.setText("Desvio Padrão");
        btnDesvioPadraoProteinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesvioPadraoProteinasActionPerformed(evt);
            }
        });

        txtDesvioPadraoProteinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDesvioPadraoProteinasActionPerformed(evt);
            }
        });

        btnvarianciaprot.setText("Variância");
        btnvarianciaprot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvarianciaprotActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel44)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(310, 310, 310)
                                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel50)
                                                .addComponent(jLabel51)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel42)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtPAmostra2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel45)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtPAmostra1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel46)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtFatorConexao, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel43)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtFatorConexao2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel52)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtPAmostra3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel40)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtFatorConexao3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel47)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtVolume))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel41)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtVolume3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel48)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtVolume2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnCalcularprot3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtCalcularProt3))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnCalcularprot1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtCalcularProt1))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnCalcularprot2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtCalcularProt2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnInserirProteinas, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnvarianciaprot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMediaProt, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMediaProt, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDesvioPadraoProteinas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDesvioPadraoProteinas, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCalcularprot1)
                        .addComponent(txtCalcularProt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPAmostra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel45)
                        .addComponent(jLabel46)
                        .addComponent(txtFatorConexao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel47)
                        .addComponent(txtVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jLabel50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(txtPAmostra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43)
                    .addComponent(txtFatorConexao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48)
                    .addComponent(txtVolume2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcularprot2)
                    .addComponent(txtCalcularProt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPAmostra3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel52)
                        .addComponent(jLabel40)
                        .addComponent(txtFatorConexao3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel41)
                        .addComponent(txtVolume3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCalcularprot3)
                        .addComponent(txtCalcularProt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMediaProt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMediaProt))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDesvioPadraoProteinas)
                        .addComponent(txtDesvioPadraoProteinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserirProteinas)
                    .addComponent(btnvarianciaprot)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMediaProtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediaProtActionPerformed
        // TODO add your handling code here:
        double resultprot, resultprot2, resultprot3, mediaProt;
        
        resultprot = Double.parseDouble(txtCalcularProt1.getText());
        resultprot2 = Double.parseDouble(txtCalcularProt2.getText());
        resultprot3 = Double.parseDouble(txtCalcularProt3.getText());

        mediaProt = (resultprot + resultprot2 + resultprot3) / 3;

         txtMediaProt.setText(String.valueOf(mediaProt));
    }//GEN-LAST:event_btnMediaProtActionPerformed

    private void txtPAmostra3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPAmostra3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPAmostra3ActionPerformed

    private void btnCalcularprot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularprot1ActionPerformed
        // TODO add your handling code here:
        double vp1, vp2, vp3, resultprot1;

        vp1 = Double.parseDouble (txtPAmostra1.getText());
        vp2 = Double.parseDouble(txtFatorConexao.getText());
        vp3 = Double.parseDouble(txtVolume.getText());

        resultprot1 = (4 * 6.25 * vp2 *100 * vp3) / vp1;

        txtCalcularProt1.setText(String.valueOf(resultprot1));
    }//GEN-LAST:event_btnCalcularprot1ActionPerformed

    private void txtPAmostra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPAmostra1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPAmostra1ActionPerformed

    private void txtPAmostra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPAmostra2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPAmostra2ActionPerformed

    private void txtCalcularProt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalcularProt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalcularProt1ActionPerformed

    private void btnInserirProteinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirProteinasActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_btnInserirProteinasActionPerformed

    private void btnDesvioPadraoProteinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesvioPadraoProteinasActionPerformed
        double n1, n2, n3, somatorioProt, despadraoProt;
        double resultProt, resultProt2, resultProt3, mediaproteinas;

        n1 = Double.parseDouble (txtCalcularProt1.getText());
        n2 = Double.parseDouble(txtCalcularProt2.getText());
        n3 = Double.parseDouble(txtCalcularProt3.getText());
        somatorioProt = (Math.pow(n1,2)) + (Math.pow(n2,2)) + (Math.pow(n3, 2));

        resultProt = Double.parseDouble(txtCalcularProt1.getText());
        resultProt2 = Double.parseDouble(txtCalcularProt2.getText());
        resultProt3 = Double.parseDouble(txtCalcularProt3.getText());

        mediaproteinas = (resultProt + resultProt2 + resultProt3) / 3;

        despadraoProt = Math.sqrt (somatorioProt - 3 * Math.pow(mediaproteinas,2) / 3 - 1);
        txtDesvioPadraoProteinas.setText(String.valueOf(despadraoProt));
    }//GEN-LAST:event_btnDesvioPadraoProteinasActionPerformed

    private void btnCalcularprot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularprot2ActionPerformed
        // TODO add your handling code here:
        double vp1, vp2, vp3, resultprot2;

        vp1 = Double.parseDouble (txtPAmostra2.getText());
        vp2 = Double.parseDouble(txtFatorConexao2.getText());
        vp3 = Double.parseDouble(txtVolume2.getText());

        resultprot2 = (4 * 6.25 * vp2 *100 * vp3) / vp1;

        txtCalcularProt2.setText(String.valueOf(resultprot2));
    }//GEN-LAST:event_btnCalcularprot2ActionPerformed

    private void btnCalcularprot3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularprot3ActionPerformed
        // TODO add your handling code here:
        double vp1, vp2, vp3, resultprot3;

        vp1 = Double.parseDouble (txtPAmostra3.getText());
        vp2 = Double.parseDouble(txtFatorConexao3.getText());
        vp3 = Double.parseDouble(txtVolume3.getText());

        resultprot3 = (4 * 6.25 * vp2 *100 * vp3) / vp1;

        txtCalcularProt3.setText(String.valueOf(resultprot3));
    }//GEN-LAST:event_btnCalcularprot3ActionPerformed

    private void txtDesvioPadraoProteinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDesvioPadraoProteinasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDesvioPadraoProteinasActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnvarianciaprotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvarianciaprotActionPerformed
        // TODO add your handling code here:
        double n1, n2, n3, somatorioProt;
        double resultProt, resultProt2, resultProt3, mediaproteinas;
        
        resultProt = Double.parseDouble(txtCalcularProt1.getText());
        resultProt2 = Double.parseDouble(txtCalcularProt2.getText());
        resultProt3 = Double.parseDouble(txtCalcularProt3.getText());
        mediaproteinas = (resultProt + resultProt2 + resultProt3) / 3;
        
        n1 = Double.parseDouble (txtCalcularProt1.getText());
        n2 = Double.parseDouble(txtCalcularProt2.getText());
        n3 = Double.parseDouble(txtCalcularProt3.getText());
        somatorioProt = (Math.pow(n1,2)) + (Math.pow(n2,2)) + (Math.pow(n3, 2));


    }//GEN-LAST:event_btnvarianciaprotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proteinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proteinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proteinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proteinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Proteinas dialog = new Proteinas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularprot1;
    private javax.swing.JButton btnCalcularprot2;
    private javax.swing.JButton btnCalcularprot3;
    private javax.swing.JButton btnDesvioPadraoProteinas;
    private javax.swing.JButton btnInserirProteinas;
    private javax.swing.JButton btnMediaProt;
    private javax.swing.JButton btnvarianciaprot;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtCalcularProt1;
    private javax.swing.JTextField txtCalcularProt2;
    private javax.swing.JTextField txtCalcularProt3;
    private javax.swing.JTextField txtDesvioPadraoProteinas;
    private javax.swing.JTextField txtFatorConexao;
    private javax.swing.JTextField txtFatorConexao2;
    private javax.swing.JTextField txtFatorConexao3;
    private javax.swing.JTextField txtMediaProt;
    private javax.swing.JTextField txtPAmostra1;
    private javax.swing.JTextField txtPAmostra2;
    private javax.swing.JTextField txtPAmostra3;
    private javax.swing.JTextField txtVolume;
    private javax.swing.JTextField txtVolume2;
    private javax.swing.JTextField txtVolume3;
    // End of variables declaration//GEN-END:variables
}
